<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Paises;

class PaisesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Paises::create(['name' => 'Aruba','code' => 'ABW','code2' => 'AW','continent' => 'North America']);
        Paises::create(['name' => 'Afghanistan','code' => 'AFG','code2' => 'AF','continent' => 'Asia']);
        Paises::create(['name' => 'Angola','code' => 'AGO','code2' => 'AO','continent' => 'Africa']);
        Paises::create(['name' => 'Anguilla','code' => 'AIA','code2' => 'AI','continent' => 'North America']);
        Paises::create(['name' => 'Albania','code' => 'ALB','code2' => 'AL','continent' => 'Europe']);
        Paises::create(['name' => 'Andorra','code' => 'AND','code2' => 'AD','continent' => 'Europe']);
        Paises::create(['name' => 'Netherlands Antilles','code' => 'ANT','code2' => 'AN','continent' => 'North America']);
        Paises::create(['name' => 'United Arab Emirates','code' => 'ARE','code2' => 'AE','continent' => 'Asia']);
        Paises::create(['name' => 'Argentina','code' => 'ARG','code2' => 'AR','continent' => 'South America']);
        Paises::create(['name' => 'Armenia','code' => 'ARM','code2' => 'AM','continent' => 'Asia']);
        Paises::create(['name' => 'American Samoa','code' => 'ASM','code2' => 'AS','continent' => 'Oceania']);
        Paises::create(['name' => 'Antarctica','code' => 'ATA','code2' => 'AQ','continent' => 'Antarctica']);
        Paises::create(['name' => 'French Southern territories','code' => 'ATF','code2' => 'TF','continent' => 'Antarctica']);
        Paises::create(['name' => 'Antigua and Barbuda','code' => 'ATG','code2' => 'AG','continent' => 'North America']);
        Paises::create(['name' => 'Australia','code' => 'AUS','code2' => 'AU','continent' => 'Oceania']);
        Paises::create(['name' => 'Austria','code' => 'AUT','code2' => 'AT','continent' => 'Europe']);
        Paises::create(['name' => 'Azerbaijan','code' => 'AZE','code2' => 'AZ','continent' => 'Asia']);
        Paises::create(['name' => 'Burundi','code' => 'BDI','code2' => 'BI','continent' => 'Africa']);
        Paises::create(['name' => 'Belgium','code' => 'BEL','code2' => 'BE','continent' => 'Europe']);
        Paises::create(['name' => 'Benin','code' => 'BEN','code2' => 'BJ','continent' => 'Africa']);
        Paises::create(['name' => 'Burkina Faso','code' => 'BFA','code2' => 'BF','continent' => 'Africa']);
        Paises::create(['name' => 'Bangladesh','code' => 'BGD','code2' => 'BD','continent' => 'Asia']);
        Paises::create(['name' => 'Bulgaria','code' => 'BGR','code2' => 'BG','continent' => 'Europe']);
        Paises::create(['name' => 'Bahrain','code' => 'BHR','code2' => 'BH','continent' => 'Asia']);
        Paises::create(['name' => 'Bahamas','code' => 'BHS','code2' => 'BS','continent' => 'North America']);
        Paises::create(['name' => 'Bosnia and Herzegovina','code' => 'BIH','code2' => 'BA','continent' => 'Europe']);
        Paises::create(['name' => 'Belarus','code' => 'BLR','code2' => 'BY','continent' => 'Europe']);
        Paises::create(['name' => 'Belize','code' => 'BLZ','code2' => 'BZ','continent' => 'North America']);
        Paises::create(['name' => 'Bermuda','code' => 'BMU','code2' => 'BM','continent' => 'North America']);
        Paises::create(['name' => 'Bolivia','code' => 'BOL','code2' => 'BO','continent' => 'South America']);
        Paises::create(['name' => 'Brazil','code' => 'BRA','code2' => 'BR','continent' => 'South America']);
        Paises::create(['name' => 'Barbados','code' => 'BRB','code2' => 'BB','continent' => 'North America']);
        Paises::create(['name' => 'Brunei','code' => 'BRN','code2' => 'BN','continent' => 'Asia']);
        Paises::create(['name' => 'Bhutan','code' => 'BTN','code2' => 'BT','continent' => 'Asia']);
        Paises::create(['name' => 'Bouvet Island','code' => 'BVT','code2' => 'BV','continent' => 'Antarctica']);
        Paises::create(['name' => 'Botswana','code' => 'BWA','code2' => 'BW','continent' => 'Africa']);
        Paises::create(['name' => 'Central African Republic','code' => 'CAF','code2' => 'CF','continent' => 'Africa']);
        Paises::create(['name' => 'Canada','code' => 'CAN','code2' => 'CA','continent' => 'North America']);
        Paises::create(['name' => 'Cocos Keeling Islands','code' => 'CCK','code2' => 'CC','continent' => 'Oceania']);
        Paises::create(['name' => 'Switzerland','code' => 'CHE','code2' => 'CH','continent' => 'Europe']);
        Paises::create(['name' => 'Chile','code' => 'CHL','code2' => 'CL','continent' => 'South America']);
        Paises::create(['name' => 'China','code' => 'CHN','code2' => 'CN','continent' => 'Asia']);
        Paises::create(['name' => 'CÃte dÂIvoire','code' => 'CIV','code2' => 'CI','continent' => 'Africa']);
        Paises::create(['name' => 'Cameroon','code' => 'CMR','code2' => 'CM','continent' => 'Africa']);
        Paises::create(['name' => 'Congo The Democratic Republic of the','code' => 'COD','code2' => 'CD','continent' => 'Africa']);
        Paises::create(['name' => 'Congo','code' => 'COG','code2' => 'CG','continent' => 'Africa']);
        Paises::create(['name' => 'Cook Islands','code' => 'COK','code2' => 'CK','continent' => 'Oceania']);
        Paises::create(['name' => 'Colombia','code' => 'COL','code2' => 'CO','continent' => 'South America']);
        Paises::create(['name' => 'Comoros','code' => 'COM','code2' => 'KM','continent' => 'Africa']);
        Paises::create(['name' => 'Cape Verde','code' => 'CPV','code2' => 'CV','continent' => 'Africa']);
        Paises::create(['name' => 'Costa Rica','code' => 'CRI','code2' => 'CR','continent' => 'North America']);
        Paises::create(['name' => 'Cuba','code' => 'CUB','code2' => 'CU','continent' => 'North America']);
        Paises::create(['name' => 'Christmas Island','code' => 'CXR','code2' => 'CX','continent' => 'Oceania']);
        Paises::create(['name' => 'Cayman Islands','code' => 'CYM','code2' => 'KY','continent' => 'North America']);
        Paises::create(['name' => 'Cyprus','code' => 'CYP','code2' => 'CY','continent' => 'Asia']);
        Paises::create(['name' => 'Czech Republic','code' => 'CZE','code2' => 'CZ','continent' => 'Europe']);
        Paises::create(['name' => 'Germany','code' => 'DEU','code2' => 'DE','continent' => 'Europe']);
        Paises::create(['name' => 'Djibouti','code' => 'DJI','code2' => 'DJ','continent' => 'Africa']);
        Paises::create(['name' => 'Dominica','code' => 'DMA','code2' => 'DM','continent' => 'North America']);
        Paises::create(['name' => 'Denmark','code' => 'DNK','code2' => 'DK','continent' => 'Europe']);
        Paises::create(['name' => 'Dominican Republic','code' => 'DOM','code2' => 'DO','continent' => 'North America']);
        Paises::create(['name' => 'Algeria','code' => 'DZA','code2' => 'DZ','continent' => 'Africa']);
        Paises::create(['name' => 'Ecuador','code' => 'ECU','code2' => 'EC','continent' => 'South America']);
        Paises::create(['name' => 'Egypt','code' => 'EGY','code2' => 'EG','continent' => 'Africa']);
        Paises::create(['name' => 'Eritrea','code' => 'ERI','code2' => 'ER','continent' => 'Africa']);
        Paises::create(['name' => 'Western Sahara','code' => 'ESH','code2' => 'EH','continent' => 'Africa']);
        Paises::create(['name' => 'Spain','code' => 'ESP','code2' => 'ES','continent' => 'Europe']);
        Paises::create(['name' => 'Estonia','code' => 'EST','code2' => 'EE','continent' => 'Europe']);
        Paises::create(['name' => 'Ethiopia','code' => 'ETH','code2' => 'ET','continent' => 'Africa']);
        Paises::create(['name' => 'Finland','code' => 'FIN','code2' => 'FI','continent' => 'Europe']);
        Paises::create(['name' => 'Fiji Islands','code' => 'FJI','code2' => 'FJ','continent' => 'Oceania']);
        Paises::create(['name' => 'Falkland Islands','code' => 'FLK','code2' => 'FK','continent' => 'South America']);
        Paises::create(['name' => 'France','code' => 'FRA','code2' => 'FR','continent' => 'Europe']);
        Paises::create(['name' => 'Faroe Islands','code' => 'FRO','code2' => 'FO','continent' => 'Europe']);
        Paises::create(['name' => 'Micronesia Federated States of','code' => 'FSM','code2' => 'FM','continent' => 'Oceania']);
        Paises::create(['name' => 'Gabon','code' => 'GAB','code2' => 'GA','continent' => 'Africa']);
        Paises::create(['name' => 'United Kingdom','code' => 'GBR','code2' => 'GB','continent' => 'Europe']);
        Paises::create(['name' => 'Georgia','code' => 'GEO','code2' => 'GE','continent' => 'Asia']);
        Paises::create(['name' => 'Ghana','code' => 'GHA','code2' => 'GH','continent' => 'Africa']);
        Paises::create(['name' => 'Gibraltar','code' => 'GIB','code2' => 'GI','continent' => 'Europe']);
        Paises::create(['name' => 'Guinea','code' => 'GIN','code2' => 'GN','continent' => 'Africa']);
        Paises::create(['name' => 'Guadeloupe','code' => 'GLP','code2' => 'GP','continent' => 'North America']);
        Paises::create(['name' => 'Gambia','code' => 'GMB','code2' => 'GM','continent' => 'Africa']);
        Paises::create(['name' => 'Guinea-Bissau','code' => 'GNB','code2' => 'GW','continent' => 'Africa']);
        Paises::create(['name' => 'Equatorial Guinea','code' => 'GNQ','code2' => 'GQ','continent' => 'Africa']);
        Paises::create(['name' => 'Greece','code' => 'GRC','code2' => 'GR','continent' => 'Europe']);
        Paises::create(['name' => 'Grenada','code' => 'GRD','code2' => 'GD','continent' => 'North America']);
        Paises::create(['name' => 'Greenland','code' => 'GRL','code2' => 'GL','continent' => 'North America']);
        Paises::create(['name' => 'Guatemala','code' => 'GTM','code2' => 'GT','continent' => 'North America']);
        Paises::create(['name' => 'French Guiana','code' => 'GUF','code2' => 'GF','continent' => 'South America']);
        Paises::create(['name' => 'Guam','code' => 'GUM','code2' => 'GU','continent' => 'Oceania']);
        Paises::create(['name' => 'Guyana','code' => 'GUY','code2' => 'GY','continent' => 'South America']);
        Paises::create(['name' => 'Hong Kong','code' => 'HKG','code2' => 'HK','continent' => 'Asia']);
        Paises::create(['name' => 'Heard Island and McDonald Islands','code' => 'HMD','code2' => 'HM','continent' => 'Antarctica']);
        Paises::create(['name' => 'Honduras','code' => 'HND','code2' => 'HN','continent' => 'North America']);
        Paises::create(['name' => 'Croatia','code' => 'HRV','code2' => 'HR','continent' => 'Europe']);
        Paises::create(['name' => 'Haiti','code' => 'HTI','code2' => 'HT','continent' => 'North America']);
        Paises::create(['name' => 'Hungary','code' => 'HUN','code2' => 'HU','continent' => 'Europe']);
        Paises::create(['name' => 'Indonesia','code' => 'IDN','code2' => 'ID','continent' => 'Asia']);
        Paises::create(['name' => 'India','code' => 'IND','code2' => 'IN','continent' => 'Asia']);
        Paises::create(['name' => 'British Indian Ocean Territory','code' => 'IOT','code2' => 'IO','continent' => 'Africa']);
        Paises::create(['name' => 'Ireland','code' => 'IRL','code2' => 'IE','continent' => 'Europe']);
        Paises::create(['name' => 'Iran','code' => 'IRN','code2' => 'IR','continent' => 'Asia']);
        Paises::create(['name' => 'Iraq','code' => 'IRQ','code2' => 'IQ','continent' => 'Asia']);
        Paises::create(['name' => 'Iceland','code' => 'ISL','code2' => 'IS','continent' => 'Europe']);
        Paises::create(['name' => 'Israel','code' => 'ISR','code2' => 'IL','continent' => 'Asia']);
        Paises::create(['name' => 'Italy','code' => 'ITA','code2' => 'IT','continent' => 'Europe']);
        Paises::create(['name' => 'Jamaica','code' => 'JAM','code2' => 'JM','continent' => 'North America']);
        Paises::create(['name' => 'Jordan','code' => 'JOR','code2' => 'JO','continent' => 'Asia']);
        Paises::create(['name' => 'Japan','code' => 'JPN','code2' => 'JP','continent' => 'Asia']);
        Paises::create(['name' => 'Kazakstan','code' => 'KAZ','code2' => 'KZ','continent' => 'Asia']);
        Paises::create(['name' => 'Kenya','code' => 'KEN','code2' => 'KE','continent' => 'Africa']);
        Paises::create(['name' => 'Kyrgyzstan','code' => 'KGZ','code2' => 'KG','continent' => 'Asia']);
        Paises::create(['name' => 'Cambodia','code' => 'KHM','code2' => 'KH','continent' => 'Asia']);
        Paises::create(['name' => 'Kiribati','code' => 'KIR','code2' => 'KI','continent' => 'Oceania']);
        Paises::create(['name' => 'Saint Kitts and Nevis','code' => 'KNA','code2' => 'KN','continent' => 'North America']);
        Paises::create(['name' => 'South Korea','code' => 'KOR','code2' => 'KR','continent' => 'Asia']);
        Paises::create(['name' => 'Kuwait','code' => 'KWT','code2' => 'KW','continent' => 'Asia']);
        Paises::create(['name' => 'Laos','code' => 'LAO','code2' => 'LA','continent' => 'Asia']);
        Paises::create(['name' => 'Lebanon','code' => 'LBN','code2' => 'LB','continent' => 'Asia']);
        Paises::create(['name' => 'Liberia','code' => 'LBR','code2' => 'LR','continent' => 'Africa']);
        Paises::create(['name' => 'Libyan Arab Jamahiriya','code' => 'LBY','code2' => 'LY','continent' => 'Africa']);
        Paises::create(['name' => 'Saint Lucia','code' => 'LCA','code2' => 'LC','continent' => 'North America']);
        Paises::create(['name' => 'Liechtenstein','code' => 'LIE','code2' => 'LI','continent' => 'Europe']);
        Paises::create(['name' => 'Sri Lanka','code' => 'LKA','code2' => 'LK','continent' => 'Asia']);
        Paises::create(['name' => 'Lesotho','code' => 'LSO','code2' => 'LS','continent' => 'Africa']);
        Paises::create(['name' => 'Lithuania','code' => 'LTU','code2' => 'LT','continent' => 'Europe']);
        Paises::create(['name' => 'Luxembourg','code' => 'LUX','code2' => 'LU','continent' => 'Europe']);
        Paises::create(['name' => 'Latvia','code' => 'LVA','code2' => 'LV','continent' => 'Europe']);
        Paises::create(['name' => 'Macao','code' => 'MAC','code2' => 'MO','continent' => 'Asia']);
        Paises::create(['name' => 'Morocco','code' => 'MAR','code2' => 'MA','continent' => 'Africa']);
        Paises::create(['name' => 'Monaco','code' => 'MCO','code2' => 'MC','continent' => 'Europe']);
        Paises::create(['name' => 'Moldova','code' => 'MDA','code2' => 'MD','continent' => 'Europe']);
        Paises::create(['name' => 'Madagascar','code' => 'MDG','code2' => 'MG','continent' => 'Africa']);
        Paises::create(['name' => 'Maldives','code' => 'MDV','code2' => 'MV','continent' => 'Asia']);
        Paises::create(['name' => 'Mexico','code' => 'MEX','code2' => 'MX','continent' => 'North America']);
        Paises::create(['name' => 'Marshall Islands','code' => 'MHL','code2' => 'MH','continent' => 'Oceania']);
        Paises::create(['name' => 'Macedonia','code' => 'MKD','code2' => 'MK','continent' => 'Europe']);
        Paises::create(['name' => 'Mali','code' => 'MLI','code2' => 'ML','continent' => 'Africa']);
        Paises::create(['name' => 'Malta','code' => 'MLT','code2' => 'MT','continent' => 'Europe']);
        Paises::create(['name' => 'Myanmar','code' => 'MMR','code2' => 'MM','continent' => 'Asia']);
        Paises::create(['name' => 'Mongolia','code' => 'MNG','code2' => 'MN','continent' => 'Asia']);
        Paises::create(['name' => 'Northern Mariana Islands','code' => 'MNP','code2' => 'MP','continent' => 'Oceania']);
        Paises::create(['name' => 'Mozambique','code' => 'MOZ','code2' => 'MZ','continent' => 'Africa']);
        Paises::create(['name' => 'Mauritania','code' => 'MRT','code2' => 'MR','continent' => 'Africa']);
        Paises::create(['name' => 'Montserrat','code' => 'MSR','code2' => 'MS','continent' => 'North America']);
        Paises::create(['name' => 'Martinique','code' => 'MTQ','code2' => 'MQ','continent' => 'North America']);
        Paises::create(['name' => 'Mauritius','code' => 'MUS','code2' => 'MU','continent' => 'Africa']);
        Paises::create(['name' => 'Malawi','code' => 'MWI','code2' => 'MW','continent' => 'Africa']);
        Paises::create(['name' => 'Malaysia','code' => 'MYS','code2' => 'MY','continent' => 'Asia']);
        Paises::create(['name' => 'Mayotte','code' => 'MYT','code2' => 'YT','continent' => 'Africa']);
        Paises::create(['name' => 'Namibia','code' => 'NAM','code2' => 'NA','continent' => 'Africa']);
        Paises::create(['name' => 'New Caledonia','code' => 'NCL','code2' => 'NC','continent' => 'Oceania']);
        Paises::create(['name' => 'Niger','code' => 'NER','code2' => 'NE','continent' => 'Africa']);
        Paises::create(['name' => 'Norfolk Island','code' => 'NFK','code2' => 'NF','continent' => 'Oceania']);
        Paises::create(['name' => 'Nigeria','code' => 'NGA','code2' => 'NG','continent' => 'Africa']);
        Paises::create(['name' => 'Nicaragua','code' => 'NIC','code2' => 'NI','continent' => 'North America']);
        Paises::create(['name' => 'Niue','code' => 'NIU','code2' => 'NU','continent' => 'Oceania']);
        Paises::create(['name' => 'Netherlands','code' => 'NLD','code2' => 'NL','continent' => 'Europe']);
        Paises::create(['name' => 'Norway','code' => 'NOR','code2' => 'NO','continent' => 'Europe']);
        Paises::create(['name' => 'Nepal','code' => 'NPL','code2' => 'NP','continent' => 'Asia']);
        Paises::create(['name' => 'Nauru','code' => 'NRU','code2' => 'NR','continent' => 'Oceania']);
        Paises::create(['name' => 'New Zealand','code' => 'NZL','code2' => 'NZ','continent' => 'Oceania']);
        Paises::create(['name' => 'Oman','code' => 'OMN','code2' => 'OM','continent' => 'Asia']);
        Paises::create(['name' => 'Pakistan','code' => 'PAK','code2' => 'PK','continent' => 'Asia']);
        Paises::create(['name' => 'Panama','code' => 'PAN','code2' => 'PA','continent' => 'North America']);
        Paises::create(['name' => 'Pitcairn','code' => 'PCN','code2' => 'PN','continent' => 'Oceania']);
        Paises::create(['name' => 'Peru','code' => 'PER','code2' => 'PE','continent' => 'South America']);
        Paises::create(['name' => 'Philippines','code' => 'PHL','code2' => 'PH','continent' => 'Asia']);
        Paises::create(['name' => 'Palau','code' => 'PLW','code2' => 'PW','continent' => 'Oceania']);
        Paises::create(['name' => 'Papua New Guinea','code' => 'PNG','code2' => 'PG','continent' => 'Oceania']);
        Paises::create(['name' => 'Poland','code' => 'POL','code2' => 'PL','continent' => 'Europe']);
        Paises::create(['name' => 'Puerto Rico','code' => 'PRI','code2' => 'PR','continent' => 'North America']);
        Paises::create(['name' => 'North Korea','code' => 'PRK','code2' => 'KP','continent' => 'Asia']);
        Paises::create(['name' => 'Portugal','code' => 'PRT','code2' => 'PT','continent' => 'Europe']);
        Paises::create(['name' => 'Paraguay','code' => 'PRY','code2' => 'PY','continent' => 'South America']);
        Paises::create(['name' => 'Palestine','code' => 'PSE','code2' => 'PS','continent' => 'Asia']);
        Paises::create(['name' => 'French Polynesia','code' => 'PYF','code2' => 'PF','continent' => 'Oceania']);
        Paises::create(['name' => 'Qatar','code' => 'QAT','code2' => 'QA','continent' => 'Asia']);
        Paises::create(['name' => 'RÃ©union','code' => 'REU','code2' => 'RE','continent' => 'Africa']);
        Paises::create(['name' => 'Romania','code' => 'ROM','code2' => 'RO','continent' => 'Europe']);
        Paises::create(['name' => 'Russian Federation','code' => 'RUS','code2' => 'RU','continent' => 'Europe']);
        Paises::create(['name' => 'Rwanda','code' => 'RWA','code2' => 'RW','continent' => 'Africa']);
        Paises::create(['name' => 'Saudi Arabia','code' => 'SAU','code2' => 'SA','continent' => 'Asia']);
        Paises::create(['name' => 'Sudan','code' => 'SDN','code2' => 'SD','continent' => 'Africa']);
        Paises::create(['name' => 'Senegal','code' => 'SEN','code2' => 'SN','continent' => 'Africa']);
        Paises::create(['name' => 'Singapore','code' => 'SGP','code2' => 'SG','continent' => 'Asia']);
        Paises::create(['name' => 'South Georgia and the South Sandwich Islands','code' => 'SGS','code2' => 'GS','continent' => 'Antarctica']);
        Paises::create(['name' => 'Saint Helena','code' => 'SHN','code2' => 'SH','continent' => 'Africa']);
        Paises::create(['name' => 'Svalbard and Jan Mayen','code' => 'SJM','code2' => 'SJ','continent' => 'Europe']);
        Paises::create(['name' => 'Solomon Islands','code' => 'SLB','code2' => 'SB','continent' => 'Oceania']);
        Paises::create(['name' => 'Sierra Leone','code' => 'SLE','code2' => 'SL','continent' => 'Africa']);
        Paises::create(['name' => 'El Salvador','code' => 'SLV','code2' => 'SV','continent' => 'North America']);
        Paises::create(['name' => 'San Marino','code' => 'SMR','code2' => 'SM','continent' => 'Europe']);
        Paises::create(['name' => 'Somalia','code' => 'SOM','code2' => 'SO','continent' => 'Africa']);
        Paises::create(['name' => 'Saint Pierre and Miquelon','code' => 'SPM','code2' => 'PM','continent' => 'North America']);
        Paises::create(['name' => 'Sao Tome and Principe','code' => 'STP','code2' => 'ST','continent' => 'Africa']);
        Paises::create(['name' => 'Suriname','code' => 'SUR','code2' => 'SR','continent' => 'South America']);
        Paises::create(['name' => 'Slovakia','code' => 'SVK','code2' => 'SK','continent' => 'Europe']);
        Paises::create(['name' => 'Slovenia','code' => 'SVN','code2' => 'SI','continent' => 'Europe']);
        Paises::create(['name' => 'Sweden','code' => 'SWE','code2' => 'SE','continent' => 'Europe']);
        Paises::create(['name' => 'Swaziland','code' => 'SWZ','code2' => 'SZ','continent' => 'Africa']);
        Paises::create(['name' => 'Seychelles','code' => 'SYC','code2' => 'SC','continent' => 'Africa']);
        Paises::create(['name' => 'Syria','code' => 'SYR','code2' => 'SY','continent' => 'Asia']);
        Paises::create(['name' => 'Turks and Caicos Islands','code' => 'TCA','code2' => 'TC','continent' => 'North America']);
        Paises::create(['name' => 'Chad','code' => 'TCD','code2' => 'TD','continent' => 'Africa']);
        Paises::create(['name' => 'Togo','code' => 'TGO','code2' => 'TG','continent' => 'Africa']);
        Paises::create(['name' => 'Thailand','code' => 'THA','code2' => 'TH','continent' => 'Asia']);
        Paises::create(['name' => 'Tajikistan','code' => 'TJK','code2' => 'TJ','continent' => 'Asia']);
        Paises::create(['name' => 'Tokelau','code' => 'TKL','code2' => 'TK','continent' => 'Oceania']);
        Paises::create(['name' => 'Turkmenistan','code' => 'TKM','code2' => 'TM','continent' => 'Asia']);
        Paises::create(['name' => 'East Timor','code' => 'TMP','code2' => 'TP','continent' => 'Asia']);
        Paises::create(['name' => 'Tonga','code' => 'TON','code2' => 'TO','continent' => 'Oceania']);
        Paises::create(['name' => 'Trinidad and Tobago','code' => 'TTO','code2' => 'TT','continent' => 'North America']);
        Paises::create(['name' => 'Tunisia','code' => 'TUN','code2' => 'TN','continent' => 'Africa']);
        Paises::create(['name' => 'Turkey','code' => 'TUR','code2' => 'TR','continent' => 'Asia']);
        Paises::create(['name' => 'Tuvalu','code' => 'TUV','code2' => 'TV','continent' => 'Oceania']);
        Paises::create(['name' => 'Taiwan','code' => 'TWN','code2' => 'TW','continent' => 'Asia']);
        Paises::create(['name' => 'Tanzania','code' => 'TZA','code2' => 'TZ','continent' => 'Africa']);
        Paises::create(['name' => 'Uganda','code' => 'UGA','code2' => 'UG','continent' => 'Africa']);
        Paises::create(['name' => 'Ukraine','code' => 'UKR','code2' => 'UA','continent' => 'Europe']);
        Paises::create(['name' => 'United States Minor Outlying Islands','code' => 'UMI','code2' => 'UM','continent' => 'Oceania']);
        Paises::create(['name' => 'Uruguay','code' => 'URY','code2' => 'UY','continent' => 'South America']);
        Paises::create(['name' => 'United States','code' => 'USA','code2' => 'US','continent' => 'North America']);
        Paises::create(['name' => 'Uzbekistan','code' => 'UZB','code2' => 'UZ','continent' => 'Asia']);
        Paises::create(['name' => 'Holy See Vatican City State','code' => 'VAT','code2' => 'VA','continent' => 'Europe']);
        Paises::create(['name' => 'Saint Vincent and the Grenadines','code' => 'VCT','code2' => 'VC','continent' => 'North America']);
        Paises::create(['name' => 'Venezuela','code' => 'VEN','code2' => 'VE','continent' => 'South America']);
        Paises::create(['name' => 'Virgin Islands British','code' => 'VGB','code2' => 'VG','continent' => 'North America']);
        Paises::create(['name' => 'Virgin Islands U.S.','code' => 'VIR','code2' => 'VI','continent' => 'North America']);
        Paises::create(['name' => 'Vietnam','code' => 'VNM','code2' => 'VN','continent' => 'Asia']);
        Paises::create(['name' => 'Vanuatu','code' => 'VUT','code2' => 'VU','continent' => 'Oceania']);
        Paises::create(['name' => 'Wallis and Futuna','code' => 'WLF','code2' => 'WF','continent' => 'Oceania']);
        Paises::create(['name' => 'Samoa','code' => 'WSM','code2' => 'WS','continent' => 'Oceania']);
        Paises::create(['name' => 'Yemen','code' => 'YEM','code2' => 'YE','continent' => 'Asia']);
        Paises::create(['name' => 'Yugoslavia','code' => 'YUG','code2' => 'YU','continent' => 'Europe']);
        Paises::create(['name' => 'South Africa','code' => 'ZAF','code2' => 'ZA','continent' => 'Africa']);
        Paises::create(['name' => 'Zambia','code' => 'ZMB','code2' => 'ZM','continent' => 'Africa']);
        Paises::create(['name' => 'Zimbabwe','code' => 'ZWE','code2' => 'ZW','continent' => 'Africa']);


    }
}
